name: standalone_application_updater
description: A comprehensive Flutter package for checking, downloading, and verifying standalone desktop application updates from GitHub Releases.
version: 0.0.1
repository: https://github.com/Rerurate514/standalone_application_updater/
issue_tracker: https://github.com/Rerurate514/standalone_application_updater/issues

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  archive: ^4.0.7
  collection: ^1.19.1
  crypto: ^3.0.7
  dio: ^5.9.0
  flutter:
    sdk: flutter
  freezed_annotation: ^3.1.0
  logger: ^2.6.2
  package_info_plus: ^9.0.0
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.7.1
  freezed: ^3.2.3
  json_serializable: ^6.11.3
  mockito: ^5.6.1

topics:
  - updater
  - desktop
  - github-releases
  - auto-update
  - windows

flutter:
  platforms:
    windows:
